# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='autors',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='read',
            new_name='was_read',
        ),
    ]
