# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(max_length=40)),
                ('challenge_description', models.CharField(max_length=40)),
                ('days_done', models.IntegerField(default=0)),
                ('begin_date', models.DateTimeField(verbose_name='beginning date')),
            ],
        ),
    ]
