# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='days_total',
            field=models.IntegerField(default=0),
        ),
    ]
