# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20170425_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='days_total',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='challenge_name',
            new_name='name',
        ),
    ]
