# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 21:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20170426_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='challenge_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='begin_date',
        ),
        migrations.AddField(
            model_name='challenge',
            name='begin',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 21, 27, 1, 943595, tzinfo=utc)),
        ),
    ]
