# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 00:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_auto_20170426_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='begin',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 27, 0, 39, 52, 921215, tzinfo=utc)),
        ),
    ]
