# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 22:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_auto_20170427_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='begin',
            field=models.DateField(default=datetime.date(2017, 4, 27)),
        ),
    ]
